# Usar uma imagem base leve do Node.js
FROM node:18-alpine

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Instalar o Nest CLI e TypeScript globalmente
RUN npm install -g @nestjs/cli typescript

# Copiar todos os arquivos do projeto para o contêiner
COPY . .

# Executar o build do projeto com TypeScript
RUN npm run build

# Expor a porta usada pela aplicação
EXPOSE 3000

# Comando para rodar a aplicação
CMD ["npm", "run", "start:dev"]
